---
- hosts: all
  tasks: 
  - name: install java6 on ubuntu14
    apt:
     name: openjdk-8-jre
     state: present
    when: ansible_os_family = ="Debian"

  - name: install java6 on redhat
    yum: 
     name: openjdk-8-jre
     state: present
    when: ansible_os_family = ="RedHat"
     
